package dictionary.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.menus.style.EditorMenuItemCustomizer;
import jetbrains.mps.openapi.editor.menus.style.EditorMenuItemStyle;
import jetbrains.mps.openapi.editor.menus.style.EditorMenuItemCustomizationContext;
import jetbrains.mps.editor.runtime.completion.CompletionMenuItemCustomizationContext;
import jetbrains.mps.editor.runtime.menus.EditorMenuItemModifyingConceptContextMatcher;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SProperty;
import java.util.Objects;
import jetbrains.mps.editor.runtime.menus.EditorMenuItemModifyingCustomizationContext;
import jetbrains.mps.editor.runtime.completion.CompletionItemInformation;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class IntroduceNewNoun_Styling implements EditorMenuItemCustomizer {

  @Override
  public void customize(EditorMenuItemStyle customization, EditorMenuItemCustomizationContext context) {
    if (context.get(CompletionMenuItemCustomizationContext.COMPLETION_ITEM_INFORMATION) == null) {
      return;
    }
    IntroduceNewNoun_StylingSpecific customizer = new IntroduceNewNoun_StylingSpecific();
    if (customizer.matches(context)) {
      customizer.customize(customization, context);
    }
  }

  private static class IntroduceNewNoun_StylingSpecific implements EditorMenuItemCustomizer {
    public boolean matches(EditorMenuItemCustomizationContext context) {
      return new EditorMenuItemModifyingConceptContextMatcher(CONCEPTS.NounWordRef$zJ) {
        protected boolean doMatchesContext(EditorMenuItemCustomizationContext context_) {
          return doMatchesContext_(getContextNode(context_), getContainmentLink(context_), getReference(context_), getProperty(context_)) && getCompletionItemInformation(context_) != null;
        }
        protected boolean doMatchesContext_(SNode contextNode, SContainmentLink containmentLink, SReferenceLink referenceLink, SProperty property) {
          return Objects.equals(referenceLink, LINKS.originalWord$ho3f);
        }
      }.matchesContext(context);
    }

    private SNode getContextNode(EditorMenuItemCustomizationContext context) {
      return context.get(EditorMenuItemModifyingCustomizationContext.CONTEXT_NODE);
    }
    private SContainmentLink getContainmentLink(EditorMenuItemCustomizationContext context) {
      return context.get(EditorMenuItemModifyingCustomizationContext.CONTAINMENT_LINK);
    }
    private SReferenceLink getReference(EditorMenuItemCustomizationContext context) {
      return context.get(EditorMenuItemModifyingCustomizationContext.REFERENCE_LINK);
    }
    private SProperty getProperty(EditorMenuItemCustomizationContext context) {
      return context.get(EditorMenuItemModifyingCustomizationContext.PROPERTY);
    }
    private CompletionItemInformation getCompletionItemInformation(EditorMenuItemCustomizationContext context) {
      return context.get(CompletionMenuItemCustomizationContext.COMPLETION_ITEM_INFORMATION);
    }


    @Override
    public void customize(EditorMenuItemStyle style, EditorMenuItemCustomizationContext context) {
      customize_(getContextNode(context), style, getCompletionItemInformation(context));
    }
    private void customize_(SNode contextNode, EditorMenuItemStyle style, CompletionItemInformation itemInformation) {
      if (Objects.equals(itemInformation.getDescriptionText(), "Do not use!")) {
        style.setStrikeout();
      }
    }

  }


  private static final class LINKS {
    /*package*/ static final SReferenceLink originalWord$ho3f = MetaAdapterFactory.getReferenceLink(0x1e23d6051cdb4db4L, 0x810f1fa070d0e977L, 0x3019678390111cc8L, 0x197de3ddaba9503bL, "originalWord");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NounWordRef$zJ = MetaAdapterFactory.getConcept(0x1e23d6051cdb4db4L, 0x810f1fa070d0e977L, 0x3019678390111cc8L, "dictionary.structure.NounWordRef");
  }
}
